### ISSUE TITLE
Unable to See First and Last Link in Pager

### ISSUE THREAD

**Issue by N0m0fud** [joeaudette/cloudscribe.Web.Pagination#4]
Thanks for the great code! I downloaded it and have it working (mostly) in an new MVC 6 / .NET 5 Web application. The only problem that I have run across is I am unable to get the First and Last links to display in the output page.

Here is my code:

`<cs-pager cs-paging-pagesize="@Convert.ToInt32(ViewData["PageSize"])"
                          cs-paging-pagenumber="@Convert.ToInt32(ViewData["CurrentPage"])"
                          cs-paging-totalitems="@Convert.ToInt32(ViewData["CurrPartCatCount"])"
                          cs-paging-maxpageritems="10"
                          cs-pagenumber-param="page"
                          cs-show-first-last="true"
                          cs-first-page-text="First"
                          cs-next-page-text="Next >"
                          cs-previous-page-text="< Previous"
                          cs-last-page-text="Last"
                          asp-controller="PartCategories"
                          asp-action="Index"></cs-pager>`

I am probably missing something stupid. Any help would be appreciated.

Thanks!

**Comment by joeaudette** [comment]
Thanks for the bug report! This was indeed a bug and I was able to reproduce the problem. I added the first last to one of the demo app examples.

This is now fixed in the code repository and I have published an updated nuget
https://www.nuget.org/packages/cloudscribe.Web.Pagination/1.0.0-beta6

**Comment by N0m0fud** [comment]
Works perfectly now. Thanks!

Suggestion, when the page is showing the first page or the last page, the corresponding First / Previous or Last / Next should not be clickable. The cursor changes but the links can still be clicked even though the same page is loaded.

**Comment by joeaudette** [comment]
Thanks! I had not noticed that. Fixed in beta7

**Comment by N0m0fud** [comment]
Works great for the Next / Last option but appears not fixed for the First / Previous option. Thanks!
